### ISSUE TITLE
Investigate Prometheus best practices

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#1145]
ETA: 2022Q4

As we trying to fill the gap in our service monitoring and metric publishing, it is worth investigating the best practices for Prometheus metric publishing before we invest in this task to minimize redoing the work. Things might be different in Prometheus, but these are things I learned to be aware of when using Cloudwatch and Java:

1. A metric object results in a single block with multiple properties and metadata. You would want to minimize the number of metric objects you create, and reuse an existing object to publish counters and timers whenever possible. For this reason, it is advisable to create a metric object first in the request handling and then pass it around. Prometheus might be doing things differently, but worth exploring
2. Metric objects can also be published as logs and not only for dashboarding. This adds value when metrics can be enriched with properties, such as requestID and jobID
3. Cloudwatch metrics doesn't work well with stale metrics, i.e. metrics that are published rarely such as certain edge cases or failure scenarios. The recommendation is to always publish those metrics with 0 values. I would assume the same applies for Prometheus

**Comment by wjam** [comment]
I wouldn't associate jobID or requestID with metrics as this causes problems for Prometheus due to the high cardinality [1]. I believe that a metric will always be included in the metric scrape as long a metric is registered with Prometheus, so should include the 0 values, and they will usually be registered when the application starts up.

I'm also not sure what the value is in associating such granular information with metrics. I've always found it better to have all log statements include per-request information (e.g. OTEL trace ID, job ID), and then check the Prometheus metrics for the time range of those log statements.

[1] CAUTION: Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values. (https://prometheus.io/docs/practices/naming/)

**Comment by wjam** [comment]
Also just realised that 'include job/trace ID' shoud really be a ticket :)
