### ISSUE TITLE
Bacalhau Roadmap

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#1151]
NOTE: This is a root issue. All children should be mapped here. Do not remove items, only add to here.

children:

- [x] #1220
- [x] #1221
- [x] #1261
- [x] #1265
- [ ] #2179
- [ ] #1262
- [ ] #1263
- [ ] #1234
- [ ] #1248
- [ ] #1311
- [ ] #1318
- [ ] #1242
- [ ] #1249
- [ ] #1356
- [ ] #1317

**Comment by momack2** [comment]
hey @aronchick - can I have a TLDR version of your roadmap that includes 5 milestones or less in the same form as the FVM roadmap? I'm thinking "GA Launch", "Ship onboarding for XYZ SDKs / onboarding flows", etc - each milestone should be worth writing a "shipped" blog post about. I'd really like to link to these milestones from the EngRes and Filecoin roadmaps - but right now there are way too many things here to figure out what to point to.

**Comment by aronchick** [comment]
Happy to do whatever! The issue is the FVM roadmap is way smaller in scope - e.g. it only talks about a very specific deliverable (developer tooling) relevant for a specific audience (filecoin developers).

Would you like us to scope down to this level? Or would you like one deliverable by segment/audience? Just lemme know!

**Comment by wesfloyd** [comment]
Woops - sorry 🤦‍♂️

**Comment by momack2** [comment]
I disagree that the FVM roadmap is smaller in scope. There is a lot of partnership, DX, engineering, security, and collab work embedded in each of these milestones - but they've done the hard work of boiling down the capabilities into a single "big rock" that marks a large xfunc upgrade in capabilities and value creation. I'd like to see you find these "big rocks" for bacalhau across threads and user groups - really judging by when someone outside the project would *care* and get to make use of an important step function upgrade in utility. Those "outside" folks could be end users or developer integrations (ex via FVM contracts to call compute over data), but milestones that are only about internal bookkeeping / incremental progress should be kept on more work-oriented trackers (instead of this "stakeholder" level roadmap).

**Comment by momack2** [comment]
@aronchick can you please come to my office hours and we can try to work through some better milestones for Cod? I think this would really help the project to align on these!

**Comment by lukemarsden** [comment]
Hey @momack2, I've updated our [starmap](https://starmap.site/roadmap/github.com/bacalhau-project/bacalhau/issues/1151#simple) 
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/264658/225983334-97b3b4b6-113e-491c-8e81-fc1d45189a1e.png">

With a new top-level [Engineering - 1.0 Launch - Projects issue](https://github.com/bacalhau-project/bacalhau/issues/2179) issue:

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/264658/225983476-e797ba90-1c4d-460a-91f5-990fab1efeb5.png">

This hopefully catures the "big rocks" for Bacalhau across threads and user groups. I've added a description to each of the issues in https://github.com/bacalhau-project/bacalhau/issues/2179 which hopefully articulates the user-facing value. Happy to receive any feedback on how to make these better. Thanks!
