### ISSUE TITLE
Estuary TestUpload test is flaky

### ISSUE THREAD

**Issue by wjam** [bacalhau-project/bacalhau#1271]
TestUpload regularly fails in CI at `pkg/publisher/estuary/publisher_test.go:58` with the error `undefined response type`. This is probably because the test is communicating with _real_ Estuary and Estuary is known to be flaky. The test should probably be changed to talk to a local dummy server instead of the real one.

Example test failure:
```
Failed
=== RUN   TestUpload
    publisher_test.go:58: 
        	Error Trace:	/home/circleci/repo/pkg/publisher/estuary/publisher_test.go:58
        	Error:      	Received unexpected error:
        	            	undefined response type
        	Test:       	TestUpload
--- FAIL: TestUpload (0.26s)
```

https://app.circleci.com/pipelines/github/filecoin-project/bacalhau/2111/workflows/0eee717b-12ba-48b1-b9f0-58d5c261d1e1/jobs/15304/steps

**Comment by simonwo** [comment]
The point of this test really is to talk to a real server – because Estuary is unpredictable i.e. it doesn't necessarily behave in the way that it advertises, so a local dummy wouldn't be catching the problems this real test is designed to. If this test is flaky, then our code is flaky too and the test is here to highlight that. 

So I'd rather find a way to keep the test against a real server but make it not burdensome for developers?

**Comment by simonwo** [comment]
Estuary test only runs against Estuary if the ESTUARY_API_KEY is set. I've un-set it in CI for now. 

We can decide what to do next when Estuary team have dealt with https://github.com/application-research/estuary/issues/567.

**Comment by wjam** [comment]
Test, or the service or configuration, appears to no longer be flaky
