### ISSUE TITLE
Concurrent jobs download URL inputs multiple times

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#1888]
When we submit jobs with URL input, each compute node makes its own web request to fetch the resource. 

This is bad because:

* In general the requests are not destined to return the same data. Concurrent jobs are meant to be identical, and so should have the same input data.
* Each compute node requesting the data places an unnecessary and potentially unwelcome load on the remote servers, and is partly the reason we have to limit maximum concurrency.

We should ensure each compute node gets the same data and we don’t unnecessarily load the remote servers.

**Comment by simonwo** [comment]
@simonwo: 
> This is a reproducability requirement – otherwise the data used in the job is not really captured in the job spec (assuming the general case of non-idempodent HTTP results).
>
> It is also a determinism requirement – the powerful principle that we should retain is that "the same job running concurrently over all nodes should be doing the same work at every node", which is the basis for determinisitic verification. Right now we allow different compute nodes to receive different URL inputs which in the general case makes it not possible to deterministically verify the results and spot bad actors. It's also a safety requirement – we shouldn't allow people to DOS remote sites by specifying some large remote input and --concurrency=1000.
>
> So there is a job for the requester here in downloading these inputs once, caching them accessibly (e.g. on IPFS), and then ensuring each compute node receives the same CIDs. Again, in general it involves being able to identify the StorageSpecs within each spec. Again, it would be poor UX and render the URL inputs flag useless to require the client to do this just to ensure sane computation.

@wdbaruni:
> Now we need to solve this for S3 content as well as the are also mutable. It should've been the user's responsibility to make sure the content doesn't change while the job is executing, or they can provide checksum for the content which allows failing the job if the checksum doesn't match the downloaded content, similar to what we do with S3 inputs

**Comment by simonwo** [comment]
A checksum sounds like a good compromise, but I don't expect allowing the users to add one will get them to do it. 

Would we be happy with a reuqester that could uplift the checksum of input storage specs – so we don't need to have storage available at the requester for caching, but we still get the ability to detect differing inputs across the compute nodes?

**Comment by wdbaruni** [comment]
Yeah I do understand we can do this with URL inputs and allow the Requester to populate the checksum (There can be issues with large inputs and having to download the content twice in different  nodes to execute a job, but lets put those on the side). The problem is you can't do this with all input types, and definitely not with S3 as the Requester won't have permission to get the object's checksum, and you can define an S3 prefix which won't have a checksum. More into this [here](https://pl-strflt.notion.site/S3-Content-Identifier-cd4d73528df6404ebc3bbcd9db2190fa)

So letting users get into the habit of defining things explicitly may not be the worse thing if they really do care about reproducibility instead of us doing some magic on their behalf that might result in unpredicted behaviour, or very inefficient execution.
