### ISSUE TITLE
Cache docker manifests

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2254]
The compute node will often ask docker registries for information about specific images, in order to determine what platforms that image is available for.  We rely on the docker client to do this for us, using information we provide. Unfortunately, some registries, notably the default docker registry, implement rate limiting reducing the number of calls that can be made in any 24 hour period. This has been a recent problem as we make more requests, we hit the rate limit more often.

We should implement a cache, storing the results of reading image manifests. This will dramatically reduce the number of times we get near to our rate limit. For each `image:tag` (or `user/image:tag` or `server/user/image:tag`) we would expect one single JSON file, but we would have to implement rules to vary how long the cached item should live in the cache. These are:

* 1 hour for untagged images, or images using the latest tag.  This will minimise the impact on our hourly rate limit, and still provide flexibility for users that have a workflow using `latest`
* 1 day if the image has a tag. Although tags can change over time, they do so only rarely.
* Permanently if the image is specified using a digest as that is immutable. We may want to implement an expiry time if it is not used for a noticeable period of time. 

Optional: Although these lifetimes are reasonable, we may want to provide a mechanism to clear the cache (either entirely, for a specific name (server/user/image:tag), or for old/unused manifests).  

Whilst it seems sensible to implement a cache per compute node, it is entirely possible to run more than one compute node on a machine, and therefore a shared cache seems more efficient.  

Implementation tbd, but either a filesystem based cache, or a shared sqlite DB, may work depending on preference for pain-points.  

- File-based cache can be atomic within the same filesystem, but there is limited metadata available, and there's a fair chance that `atime` may be disabled making last access time more difficult to ascertain.
- A shared sqlite database may appear more flexible in recording metadata, and multiple readers is fine, but a writer much obtain an exclusive lock on the entire database and must wait for shared locked to be complete.

**Comment by frrist** [comment]
I want to flag that the description has the potential to clash with https://github.com/bacalhau-project/bacalhau/issues/2255 (recent comments in #2255 came from conversation in https://github.com/bacalhau-project/bacalhau/issues/2351). 

### latest and versioned tags
I believe that compute nodes should never encounter a `latest` tag or an untagged image. As a reference, the [Kubernetes documentation advises against using the `latest` tag](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy). While some users may still want to use it, we can accommodate them by resolving the `latest` tag to a specific image digest at the Requester level. This ensures that highly concurrent Docker jobs using `latest` will run the same image. Since tags are (sadly) mutable I would too like to resolve these at the Requester level, however I have less strong feelings on this since its rare for tags to change.

In an open network with third-party Requester and Compute nodes, the decision to permit the `latest` tag will depend on their developers. However, in our implementation, we should require the Requester level to resolve the `latest` tag and prevent any specification with the `latest` reference from reaching a compute node.

My point here is that I would like to prevent compute nodes from caching (or even seeing!) a `latest` tag and to instead handle caching of this information via the Requester node(s). And ideally resolve tagged versions in a similar fashion.

### image digest
In full agreement that these can be cached by compute nodes.
