### ISSUE TITLE
Jobs only are scheduled to one node while most of the nodes are idle

### ISSUE THREAD

**Issue by js-ts** [bacalhau-project/bacalhau#2421]
![image](https://user-images.githubusercontent.com/79689323/235361749-160914fa-2dc8-47f8-a4fa-e28a11473889.png)

**Comment by frrist** [comment]
Inspecting the node info yields the following results. `QmT9AvEq`, `QmT69eMH`, and `Qmd1LXFU` are running outdated versions of the binary and may not be accepting on jobs due to this. Meaning there are only 5 nodes capable of accepting work. It's also worth noting that `QmXaXu9N` is too running jobs, although it is not as tasked as `QmdZQ7Zb`. Lastly, and this is a guess, lexicographical nodeID `QmdZQ7Zb` sorts before `QmXaXu9N`, so for jobs that require a concurrency of 1 it may be returned first from the listed nodes. `QmdZQ7Zb` isn't necessarily overloaded either so it seems reasonable for it to accept work given the above usage.

It would be helpful to understand the nature of the jobs being ran by `QmdZQ7Zb`
```
{
  "key": "QmT9AvEq",
  "gitversion": "v0.3.23",
  "labels": {
    "owner": "docs-quick-start"
  },
  "RunningExecutions": 0,
  "EnqueuedExecutions": 0
}
{
  "key": "QmT69eMH",
  "gitversion": "v0.3.25",
  "labels": {
    "Architecture": "amd64",
    "GPU-0": "NVIDIA GeForce RTX 3090",
    "GPU-0-Memory": "24576 MiB",
    "GPU-1": "NVIDIA GeForce RTX 3090",
    "GPU-1-Memory": "24576 MiB",
    "Operating-System": "linux",
    "env": "prod",
    "git-lfs": "False",
    "name": "saturnia_len20"
  },
  "RunningExecutions": 0,
  "EnqueuedExecutions": 0
}
{
  "key": "Qmd1LXFU",
  "gitversion": "v0.3.25",
  "labels": {
    "Architecture": "amd64",
    "GPU-0": "NVIDIA A10",
    "GPU-0-Memory": "23028 MiB",
    "Operating-System": "linux",
    "git-lfs": "False"
  },
  "RunningExecutions": 0,
  "EnqueuedExecutions": 0
}
{
  "key": "QmXaXu9N",
  "gitversion": "v0.3.28",
  "labels": {
    "Architecture": "amd64",
    "Operating-System": "linux",
    "git-lfs": "True",
    "owner": "bacalhau"
  },
  "RunningExecutions": 5,
  "EnqueuedExecutions": 0
}
{
  "key": "QmYA2p8Q",
  "gitversion": "v0.3.28",
  "labels": {
    "Architecture": "amd64",
    "Operating-System": "linux",
    "git-lfs": "False",
    "who": "FORREST"
  },
  "RunningExecutions": 0,
  "EnqueuedExecutions": 0
}
{
  "key": "QmYgxZiy",
  "gitversion": "v0.3.28",
  "labels": {
    "Architecture": "amd64",
    "Operating-System": "linux",
    "git-lfs": "True",
    "owner": "bacalhau"
  },
  "RunningExecutions": 0,
  "EnqueuedExecutions": 0
}
{
  "key": "QmdZQ7Zb",
  "gitversion": "v0.3.28",
  "labels": {
    "Architecture": "amd64",
    "Operating-System": "linux",
    "git-lfs": "True",
    "owner": "bacalhau"
  },
  "RunningExecutions": 3,
  "EnqueuedExecutions": 0
}

```

The above json was produced using the following `jq` command: `jq 'to_entries | sort_by(.value.BacalhauVersion.gitversion) | .[] | {key: .key[0:8], gitversion: .value.BacalhauVersion.gitversion, labels: .value.Labels, RunningExecutions: .value.ComputeNodeInfo.RunningExecutions, EnqueuedExecutions: .value.ComputeNodeInfo.EnqueuedExecutions}'`
