### ISSUE TITLE
Fix NewIPFSPublishers

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#2555]
The method is named incorrectly, and it makes all publishers, such as S3 and Noop, available 
Its registering an IPFS publisher as an estuary publisher, resulting in nodes advertising estuary is installed when its not (its just IPFS

**Comment by simonwo** [comment]
The reason for this was/is that:
* Estuary was/is our preferred publishing platform, because data there gets written into Filecoin = good
* We want as many jobs to use this as possible, so the default on the CLI is today still Estuary
* But we don't want jobs to fail if Estuary isn't installed, and we just want a fallback to IPFS – hence we make sure that the Estuary publisher is always installed and just uses IPFS if necessary.

Not ideal, but that's the reasoning.

Is there a case for even having the Estuary type separate from IPFS? Could we just make the IPFS publisher a fanout publisher that sends to both IPFS and Estuary, if installed?

**Comment by aronchick** [comment]
Still needed?
