### ISSUE TITLE
Retrieving S3 credentials to verify they are installed is slow - +5 seconds

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#2562]
The method `HasValidCredentials` (called via `IsInstalled`): https://github.com/bacalhau-project/bacalhau/blob/2ff76768acfe68c2a913b3c1b019fab024a835e0/pkg/s3/utils.go#L26-L33 (line 27) is taking ~5 seconds per call and significantly slowing down the speed at which our tests run. We should seek alternative means of verifying an s3 storage provider is installed for our testing needs. cc @wdbaruni do you have any ideas here?

**Comment by rossjones** [comment]
At the moment we're basis our answer to whether it is installed based on whether we currently have credentials or not configured on the server. This seems reasonably limited if people want to access their own S3 resources with their own IAM roles.

Once we have a useful way of providing secrets to the execution, perhaps adding support for layers of credentials to the StorageSpec for Inputs/Outputs might be a good approach to take.  This could be the required env vars for S3, an Authorization header for HTTP, a key to decode the download etc.

**Comment by wdbaruni** [comment]
The reason it takes long is that AWS client by default tries to reach EC2 metadata service to extract information about the current host if it is an EC2 instance. Since we are not running the tests on EC2, it times out after ~5 seconds. This also slows down the startup time of `bacalhau serve`, but doesn't impact the processing of jobs.

One option is to set [`AWS_EC2_METADATA_DISABLED`](https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-envvars.html#envvars-list-AWS_EC2_METADATA_DISABLED) env variable to true for all of our test cases. Unfortunately the aws-go-sdk doesn't support setting the timeout window or max attempts to call the metadata service https://github.com/aws/aws-sdk-go/issues/3495

**Comment by simonwo** [comment]
> One option is to set [AWS_EC2_METADATA_DISABLED](https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-envvars.html#envvars-list-AWS_EC2_METADATA_DISABLED) env variable to true for all of our test cases.

I have this set locally and it speeds up the tests as desired.

**Comment by simonwo** [comment]
> This also slows down the startup time of `bacalhau serve`.

Actually, checking which providers are installed is now in a separate goroutine and the node only publishes NodeInfo when the process is complete. So the node starts up immediately but doesn't _announce_ itself until the check is complete.
