### ISSUE TITLE
Define Envelope schema for request/response backwards compatibility 

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#2701]
In a similar vein to #2700 and motivated by @wdbaruni's comment [here](https://github.com/bacalhau-project/bacalhau/pull/2637#discussion_r1278624531). We need to define an Envelop structure for wrapping requests and responses for services such as the JobStore and Compute<->Executor RPC to help maintain backward compatibility with future changes.

One proposed example of the schema could be:
```protobuf
syntax = "proto3";

message Envelope {
    string version = 1;
    string timestamp = 2;
    Metadata metadata = 3;
    bytes payload = 4; // or maybe use `any`
    string checksum = 5;

    message Metadata {
        string serialization_format = 1;
        // ... any other metadata fields you need.
    }
}
```
cc @rossjones @wdbaruni

**Comment by rossjones** [comment]
A similar envelope structure will be necessary for the storage of data, initially to handle the ser/deser of the payload[1] but shortly thereafter  for proper tracking of versions of data.  I started one for the ser/deser (supporting json/gob) at https://github.com/bacalhau-project/bacalhau/blob/main/pkg/jobstore/envelope.go but am planning to move it over to use this impl.

One thought I had was that it might be clunky creating these Envelopes all the time (particularly for Job, JobState etc) and thought it might be useful to define a few interfaces around it's construction, so that we can construct them from any type that implements that interface.  In particular I thought, version and metadata might be best extracted from an interface like 

```
type VersionedOjbect struct {
    Version() int 
    Metadata() Metadata 
}
```
so that we can provide `envelope.From(VersionedObject) *Envelope` and have a full constructed Envelope back. 

[1] this is because we spend a lot of time with json serlialisation and there aren't a lot of advantages to it in this use-case.
