### ISSUE TITLE
`--download` and `--follow` are incompatible

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#2746]
```
bacalhau docker run --download --follow ubuntu date
```

The `--download` flag is silently ignored and no results are downloaded when the job ends. There's no reason this shouldn't work.

**Comment by rossjones** [comment]
This is likely because after following logs, the code returns early at https://github.com/bacalhau-project/bacalhau/blob/main/cmd/util/printer/print.go#L98 and so never gets to https://github.com/bacalhau-project/bacalhau/blob/main/cmd/util/printer/print.go#L148-L152

We should probably handle any error at L98 and continue with the rest of the function.

**Comment by wdbaruni** [comment]
confirming this is still an issue
```
bacalhau docker run --follow  --download ubuntu -- sh -c 'for i in $(seq 1 5); do echo "Printing $i"; sleep 1; done'
Using default tag: latest. Please specify a tag/digest for better reproducibility.
Job successfully submitted. Job ID: 1e0cb796-e145-41e4-931f-778cb29bb572
Waiting for logs... (Enter Ctrl+C to exit at any time, your job will continue running):

Printing 1
Printing 2
Printing 3
Printing 4
Printing 5
```

**Comment by wdbaruni** [comment]
`--download ` is no longer an option for docker run
