### ISSUE TITLE
Functionality to avoid having to providing a peer ID for connections

### ISSUE THREAD

**Issue by alabdao** [bacalhau-project/bacalhau#2837]
I'm looking for functionality similar to `--ipfs-connect` where operator has the ability to provide multiaddr without specifying a peer ID `--ipfs-connect /dns4/localhost/tcp/5001` (taken from [docs](https://docs.bacalhau.org/running-node/quick-start-docker/#start-a-public-bacalhau-node))

It would be great to have this functionality available for `--peer` flag where ID could be optionally provided or another flag like `--peer-connect` that accepts multiaddr without peer ID.

This provides operator with ability to avoid having to provide a hard-coded peer ID in dynamic environments where persistence is not necessary such as local development environment with docker-compose or non-local dynamic containerized environment where state isn't persisted.

Slack conversation: https://bacalhauproject.slack.com/archives/C052BAZJVEU/p1695046281440619

**Comment by rossjones** [comment]
This is part resolved by https://github.com/bacalhau-project/bacalhau/pull/2897 which works with the caveats that:

 * You specify the public API endpoint of the requester node in the http multiaddr
 * Your peering port is 1235 (the default).
 
 The hard-coded default peering port is because there's currently no clean way to obtain the port that the requester node is listening on, and so we temporarily just pick the default.  

Will close this when/if we come up with a cleaner method where the p2p listen port is discoverable.

**Comment by rossjones** [comment]
Great, feel free to close this ticket if you're happy with it, and I'll track the issue with the fixed listening port elsewhere.
