### ISSUE TITLE
Job selection probes are misconfigured for Compute and Requester Nodes

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#2898]
> Hi. With Bacalhau 1.1.0, I don't see `--job-selection-probe-http` cli arg working This worked fine in v1.0.3.
> I'm running with `LOG_LEVEL='debug'`. Is there a particular log line that I could look for that shows that probe endpoint being called?
>
> I can see the log shows flag being passed in with correct endpoint:
> `os.Args: [bacalhau serve --node-type requester --ipfs-connect <ipfs-conenct> --private-internal-ipfs=false --labels owner=labdao --job-selection-accept-networked --job-selection-data-locality anywhere --peer none --job-selection-probe-http http://<endpoint>]`

**Comment by wdbaruni** [comment]
related https://bacalhauproject.slack.com/archives/C052BAZJVEU/p1697312898982309

**Comment by wdbaruni** [comment]
The issue is related to how we map CLI flags to compute and request config. The job selection flags are linked to `NodeRequesterXXX` key/prefix. 
https://github.com/bacalhau-project/bacalhau/blob/75ce16214a6f9ccf8307adc9a1b0d64750124265/cmd/util/flags/configflags/job_selection.go#L20

The flags are working fine with the requester node, and the requester is able to set its own job selection policy just fine since it is reading config with key `NodeRequesterXXX`
https://github.com/bacalhau-project/bacalhau/blob/badd1ce5fd9508bd615f9a8e08bd8ce44d2eceb7/cmd/cli/serve/util.go#L57

That is not the case for the compute node since it is reading configs with key `NodeComputeXXX`
https://github.com/bacalhau-project/bacalhau/blob/badd1ce5fd9508bd615f9a8e08bd8ce44d2eceb7/cmd/cli/serve/util.go#L29

This is also visible when printing the node configs:

```
serve --node-type requester,compute --job-selection-accept-networked
...
13:37:22.561 | DBG pkg/node/config_compute.go:190 > Compute config: ...
JobSelectionPolicy:{Locality:Anywhere RejectStatelessJobs:false AcceptNetworkedJobs:false ProbeHTTP: ProbeExec:}
...

13:37:22.572 | DBG pkg/node/config_requester.go:59 > Requester config: ...
JobSelectionPolicy:{Locality:Anywhere RejectStatelessJobs:false AcceptNetworkedJobs:true ProbeHTTP: ProbeExec:}
 ...
```

Not sure what the right fix here. It doesn't look like our config supports one flag that sets multiple configurations @frrist

**Comment by frrist** [comment]
Both the Requester and the Compute node configs contain a `JobSelectionPolicy`. But I don’t see where we use the `JobSelectionPolicy` field for the requester, it looks like we never read from the value once it’s set. Would it make sense to simply remove the field from the requesters config?

**Comment by frrist** [comment]
via https://github.com/bacalhau-project/bacalhau/pull/2936
