### ISSUE TITLE
bacalhau: log job id readable

### ISSUE THREAD

**Issue by Nasfame** [bacalhau-project/bacalhau#2966]
```
bacalhau docker run --id-only --gpu 1 ghcr.io/bacalhau-project/examples/stable-diffusion-gpu:0.0.1 -- python main.py --o ./outputs --p "meme about tensorflow" 
```

### Output
```
0e9b3566-2f69-4bab-81ed-ab20886d8ff7
```

The job id to prepended with `job-id: $jobid`

**Comment by Nasfame** [comment]
Relates to #2965

**Comment by rossjones** [comment]
> The job id to prepended with job-id: $jobid

Not sure I understand. Is that what you are expecting to see? Or test you think we should in front of the ID.
The point of --id-only is so that you can use it in scripts and not need to parse the ID out of any other text.  Displaying `job-id: <JOBID>` instead will break something so someone, and will make it harder to parse.

**Comment by Nasfame** [comment]
@rossjones thanks for the clarification, if thats the case it does make sense to make the output readable
