### ISSUE TITLE
bacalhau job run --follow sometimes exit early

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#3018]
Running a job with `--follow` flag such as `bacalhau job run job.yaml --follow` is expected to wait and print execution logs. Sometimes it works as expected, while others it exit early with no message, even though the execution succeeded. 

```
[3.9]→ bacalhau job run log-processor.yaml --follow
Job successfully submitted. Job ID: j-dd1f31b8-6741-4f96-98a1-52cfc16b7a08
Waiting for logs... (Enter Ctrl+C to exit at any time, your job will continue running):

[3.9]→ 
```

**Comment by rossjones** [comment]
I've definitely seen it fail when it's waited for an execution to start and it took slightly too long (in terms of how long the log client will wait).  It should probably do a better job of waiting and not give up so easily.

**Comment by rossjones** [comment]
Possibly related, we previously didn't do a good job of waiting for the execution to be running (delta between state change and actually running). https://github.com/bacalhau-project/bacalhau/pull/3138 should improve the situation (and was necessary because `exec -f` was getting there before the code was running).

**Comment by wdbaruni** [comment]
I believe it is also related to race condition mentioned here https://github.com/bacalhau-project/bacalhau/issues/2337#issuecomment-2056453424
