### ISSUE TITLE
Fix errors when multiple bacalhau are running

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#3150]

**Comment by rossjones** [comment]
Doesn't the use of the lock file prevent this?  I've certainly seen devstack complain after a crash that it won't run because of the port/pid files.

**Comment by aronchick** [comment]
the problem is that the error (as printed) is unusable. that's what this fixed.

**Comment by frrist** [comment]
Has the PR addressing this been merged? If not should we move this back to 'Ready' as this issue is still open?

Couple things to consider when running more than one bacalhau node on a host:
1. Their ports can collided which will produce an error on startup.
2. They could be configured to use different ports via flags, but share a repo and related on-disk stores, this should probably be a different error and we could prevent it from happening with a lock file. Sounds like we already have a lock file somewhere?

**Comment by aronchick** [comment]
i think it's merged
