### ISSUE TITLE
When a bad IPFS peer is set in environment variables, should still start

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#3169]
It shouldn't prevent starting `bacalhau serve` when the IPFS peer is a bad IP

**Comment by wdbaruni** [comment]
I don't think this is a problem anymore since we moved to providing IPFS node explicitly through `--ipfs-connect`or its equivalent environment variable 

The user would expect `bacalhau serve --ipfs-connect=<multiaddr>` to fail if the provided address is incorrect or not reachable, which is the case today:
```
→ bacalhau serve --node-type=requester,compute --ipfs-connect=/ip4/127.0.0.1/tcp/5001
error creating node: failed to connect to '/ip4/127.0.0.1/tcp/5001': Post "http://127.0.0.1:5001/api/v0/id?": dial tcp 127.0.0.1:5001: connect: connection refused
```
