### ISSUE TITLE
Bacalhau fails to boot cluster due to new persistent node store 

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#3550]
```
error creating node: failed to create node info store using NATS transport connection info: failed to create key-value store: context deadline exceeded
```

The nodes are stuck in a boot loop on staging, all failing with this message after a few seconds.

```
% gcloud compute ssh bacalhau-vm-stage-1
$ sudo journalctl --follow --unit=bacalhau
```

**Comment by rossjones** [comment]
This is currently happening because we set BACALHAU_NODE_NETWORK_CLUSTER_PEERS to be a single address, which is the address of the current machine.  Jetstream doesn't like seeing an empty cluster setting, or a cluster containing the local node - it attempts to set up a RAFT network and fails.  

To fix this I've removed the variable on the staging machine until I can update the relevant bit of ops code.
