### ISSUE TITLE
dial tcp: lookup public: no such host

### ISSUE THREAD

**Issue by georgesmith9914** [bacalhau-project/bacalhau#3652]
When I am running "bacalhau get 93de7e27-f7ef-4526-8582-bed783c0cbc7", the command always returns with following error -

error downloading job: Get "http://public:6001/e-23934cf0-c35b-4ad9-8e31-4c54326fcf9e.tgz": dial tcp: lookup public: no such host

I have tried with many jobs and the error is always the same.

**Comment by georgesmith9914** [comment]
I also get this error "dial tcp: lookup public on 127.0.0.53:53: server misbehaving".
But it never succeeds.

**Comment by simonwo** [comment]
@rossjones

**Comment by rossjones** [comment]
This is unfortunately a bug, where the machine is trying to resolve a public address on that machine, but because of configuration it does not have one.  This should be resolved in the next release. Sorry. 

@georgesmith9914 I've updated the demo network to use IPFS for now, so you should be able to re-run your job and get access to the outputs.  Alternatively you can run your job with `-p ipfs` to switch publishers.

**Comment by aronchick** [comment]
@georgesmith9914 just to be clear, you can curl the endpoint "http://public" on your machine? Just making sure

**Comment by rossjones** [comment]
This is fixed now in the 1.3 release, the requester node should be configured with the `--local-publisher-address` flag which is the IP shown in the returned URL for locally published content (instead of public).
