### ISSUE TITLE
Default publisher is not getting applied

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4391]
Submitting a job with outputs and without a publisher defined is expected to have the default publisher applied in the requester side, if any, or is failed. 

However, this is not the case as we are doing client side validation and fail the job early before submission if it has result paths defined and no publisher

This has been failing since v1.4.0

```
# run node with local default publisher
bacalhau-1.4.0 serve --node-type requester,compute --repo ~/bacalhau-versions/v1.4.0/data-dir --default-publisher local

# run job with results but no publisher
→ bacalhau docker run --output outputs:/outputs ubuntu -- sh -c "echo hello > /outputs/hello.txt"
building job spec: failed to create job: publisher must be set if result paths are set

# verify job is passing if a publisher is defined
bacalhau docker run --output outputs:/outputs -p local ubuntu -- sh -c "echo hello > /outputs/hello.txt"
```

The same applies for declarative submissions, such as 
```
# publisher-default.yaml
Name: Default publisher
Type: batch
Tasks:
  - Name: main
    Engine:
      Type: docker
      Params:
        Image: ubuntu
        Parameters:
          - sh
          - -c
          - echo hello > /outputs/hello.txt
    ResultPaths:
      - Name: outputs
        Path: /outputs
```

```
→ bacalhau job run publisher-default.yaml
the job provided is invalid: task main validation failed: publisher must be set if result paths are set
```

**Comment by frrist** [comment]
The validation of tasks enforcing this behavior was introduced in https://github.com/bacalhau-project/bacalhau/pull/2802 and has thus been present since roughly [v1.1.0](https://github.com/bacalhau-project/bacalhau/releases/tag/v1.1.0).

@wdbaruni is the acceptance criteria here to 1) modify the Tasks `ValidateSubmission` method such that it is only called after the job has been transformed server side 2) modify the transformer to check if results path is defined before applying a default publisher? I believe this change may need to be landed with https://github.com/bacalhau-project/bacalhau/issues/4392 since automatically including a results path in docker jobs will cause validation of the task to fail - an is likely the reason the default was removed.

**Comment by wdbaruni** [comment]
We discussed this over our 1:1. Just moving the validation from ValidateSubmission to Validate will be enough
