### ISSUE TITLE
Remove more defaults from CLI

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#528]
ETA: 2023Q2

The current smallest possible command to execute on Bacalhau is the following:

```
 bacalhau docker run ubuntu -- /bin/true
```

Both `docker` and `ubuntu` should be defaults. Ideally, the smallest command should be:

```
bacalhau run /bin/true
```

- [ ] Default `run` to running docker unless `--determinism` flag is present
- [ ] Default `image` to be ubuntu (or other equivalent, whatever we feel like is appropriate) 
- [ ] Maybe pre-cache a set of common images we recommend on every machine?

**Comment by lukemarsden** [comment]
`bacalhau run /bin/true` is a bit _too_ magic IMO because `/bin/true` actually exists inside a default docker image, not the `/bin/true` on the system

I am open to some more autodetection though

**Comment by wdbaruni** [comment]
A default docker image, or any execution environment, might make sense not only to simplify user experience, but to also minimize users defining different images to execute simple tasks. This will reduce cost and latency in compute nodes and avoid having to pull new images for simple jobs.

If docker is the environment of choice, I would recommend creating our own image rather than ubuntu to be able to pack it with more features to enable different types of jobs, and to have more control on the image release cycle
