### ISSUE TITLE
add 5 GPUs to production network

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#899]
splitting out from #715

**Comment by lukemarsden** [comment]
GCP so far have denied our requests

**Comment by lukemarsden** [comment]
Phil is trying using different regions

**Comment by philwinder** [comment]
GCP have actually REDUCED our limits down to 2 now. I have altered the terraform code so that we have a second GPU node in Europe. That works. https://github.com/filecoin-project/bacalhau/commit/fd576f28cdfb26d3be33e774efd11de9e0714574

However, when submitting a GPU job, I can't get two GPU jobs to get scheduled at the same time.

For example, run two of these:
```
bacalhau docker run --gpu 1 jsacex/stable-diffusion-keras -- python stable-diffusion.py --o ./outputs
```

And only one will run at a time. Alternatively, run multiple of these:
```
docker run --gpu=1 nvidia/cuda:11.0.3-base-ubuntu20.04 nvidia-smi
```

And note that the node hash is always the same `QQ` at the end.

**Comment by binocarlos** [comment]
OK I think there is a bug with the capacity manager - having dug into the production nodes - I am sometimes seeing GPU jobs running in parallel and then sometimes sequentially...

When running sequentially - bids are being made and accepted by the node already running the job - which indicates there is something wrong - am writing a test now

**Comment by binocarlos** [comment]
> When running sequentially - bids are being made and accepted by the node already running the job - which indicates there is something wrong with capacity manager thinking it has capacity when it clearly does not - it's not actually starting the job, but it is bidding on it (preventing the other node who actually has the capacity from winning the bid) - am writing a test now

This is not actually true - I think the issue here is jobs were getting randomly dropped by the `CalculateJobNodeDistanceDelay` - we now have an explicit test for network latency and running GPU jobs in parallel and so we know there isn't a bug in the bidding process in this scenario

I've added a logging statement for the case when the `CalculateJobNodeDistanceDelay` function decides to drop a job so we should at least be able to identify when this is causing the above problem

**Comment by binocarlos** [comment]
Update on above - it was nothing to do with `CalculateJobNodeDistanceDelay` actually - I was totally wrong - it was compute nodes bidding out of phase and then getting stuck in a "I have reserved resources that will never be unlocked" state

https://github.com/filecoin-project/bacalhau/pull/921 is a potential fix for this

**Comment by binocarlos** [comment]
we've just done a bunch of testing and #921 has fixed the multiple scheduling problem - so - now we just need to increase our gcloud GPU quotas and we can close out this issue

**Comment by scenaristeur** [comment]
Hi , i've just discovered Bacalhau and find it's a good project. 
Interested in Stable diffusion, i've found this "Horde project" with crowdsourced GPU, could this help ? 
https://stablehorde.net/
