### ISSUE TITLE
Support Do Not Track Standard

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#94]
ETA: 2023Q2

Include in observability work

https://consoledonottrack.com/

**Comment by aronchick** [comment]
Simon / Enrico, i think one of you are working on observability?

**Comment by wjam** [comment]
Notes on consoledonottrack.com:

* The standard is about collecting telemetry on the client-side (usage tracking, adverts, crash reports, etc). The standard doesn't cover tracking server-side use.
* Some links on the website, such as the link to its own VCS, are broken. This indicates the website is unmaintained since at least 2020-10-13.
* Only netlify, tilt, & netdata adopted `DO_NOT_TRACK` whereas all of the others rejected the PRs. Others may adopted DO_NOT_TRACK but the website is unmaintained.
  * netdata appears to be moving away from `DO_NOT_TRACK` - https://github.com/netdata/netdata/pull/12126

So, while we don't track any local-only use [^1], we can use the environment variable to avoid setting up tracing and metrics.

[^1]: We don't have any to use Bacalhau without using something remote, unless you set up your own server
