### ISSUE TITLE
cli should retry

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#983]
```
luke@chunky:~$ time bacalhau docker run --concurrency 10 ubuntu echo who is fast and who is slow
Job successfully submitted. Job ID: 8d20296d-2b77-4d92-8d9f-0a12c60a7b70
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

Failure retrieving job events '8d20296d-2b77-4d92-8d9f-0a12c60a7b70': publicapi: after posting request: Job not found. ID: 8d20296d-2b77-4d92-8d9f-0a12c60a7b70


real	0m0.592s
user	0m0.176s
sys	0m0.034s
```

API requests from the CLI will be randomly round-robined between 3 of the production servers. Therefore, the CLI is racing with libp2p to distribute info about the job in the cluster. The CLI should retry for 10 seconds at least for the state to become consistent, rather than failing straight away if the node it asks about a job differs from the one it submitted it to and the former doesn't know about the job yet.

**Comment by wdbaruni** [comment]
This should be mitigated once we move to an external storage for job state instead of in-memory. Well, it depends on the type of the external storage and whether it is strongly or eventually consistent. Our goal is to use sql database, which should solve this issue without having to retry in the client side
